//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseJiraTicketsFromXml
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiraTicket
    {
        public long ID { get; set; }
        public string key { get; set; }
        public string summary { get; set; }
        public string link { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public string assignee { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string aggregatetimeoriginalestimate { get; set; }
        public string aggregatetimeremainingestimate { get; set; }
        public string aggregatetimespent { get; set; }
        public Nullable<System.DateTime> RecordCreationDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
